name: Build and Publish

on:
    push:
        branches:
            - main

jobs:
    build-playstore:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.32.6'
                channel: 'stable'

            - name: Auto versioning
              run: .github/scripts/set_version.sh prod

            - name: Decode keystore
              run: |
                echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/key.jks

            - name: Create key.properties
              run: |
                echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
                echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
                echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
                echo "storeFile=key.jks" >> android/key.properties

            - name: Install dependencies
              run: flutter pub get

            - name: Run analyzer
              run: flutter analyze

            - name: Build AAB for Play Store
              run: flutter build appbundle --release

            - name: Verify AAB exists
              run: |
                FILE=build/app/outputs/bundle/release/app-release.aab
                if [ ! -f "$FILE" ]; then
                  echo "ERROR: AAB file not found at $FILE"
                  exit 1
                fi
                echo "Found AAB file: $FILE"

            - name: Upload to Play Store Internal Track
              uses: r0adkll/upload-google-play@v1
              with:
                  serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
                  packageName: com.metsec.metsec_loyalty_app
                  releaseFiles: build/app/outputs/bundle/release/app-release.aab
                  track: internal
                  status: draft
                  changesNotSentForReview: true
